-d /home/champagnepapi/Documents/forklift/forklift/src/fork/impl/gwsynthesis/fork.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/champagnepapi/Documents/forklift/forklift/src/fork/src/forklift_top.cst
-cfg /home/champagnepapi/Documents/forklift/forklift/src/fork/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
